# Generated by Django 3.1.1 on 2020-09-16 06:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrylog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_time', models.DateTimeField(auto_now_add=True, verbose_name='Vistor entry date and time')),
                ('checkout_time', models.DateTimeField()),
                ('purpose', models.TextField(verbose_name='Purpose of visit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to='visitor.visitor')),
            ],
        ),
    ]
